# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'PangleAdExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PangleAdExample
  pod 'ADManager', :path=>'../../ADManager'
  pod 'PangleAd', :path=>'../'

  # Pods for Example 
  pod 'GeSwift'
  pod 'RxDataSources'
  pod 'RxCocoa'
  pod 'SnapKit'
end
